#!/bin/bash
# Liger: Smart concatenation tool for creating supermatrices
# version: 1.0
# written and developed by Andrew Budge

# Usage check
if [ $# -lt 2 ]; then
    echo "Usage: liger [INPUT FILES] [TAXA LIST]" >&2
    echo "Output: Supermatrix to stdout, partition file to stderr" >&2
    echo "See https://github.com/andrewbudge/Liger for more information" >&2
    exit 1
fi

INPUT_FILES=("${@:1:$#-1}")
CANONICAL_TAXA_LIST="${@: -1}"

# Check if taxa list exists
if [ ! -f "$CANONICAL_TAXA_LIST" ]; then
    echo "Error: $CANONICAL_TAXA_LIST does not exist" >&2
    exit 1
fi

# Create tmp dir
WORK_DIR=$(mktemp -d)
trap "rm -rf $WORK_DIR" EXIT

# get seq len and gen name for partition file
declare -a GENE_NAMES
declare -a GENE_LENGTHS
for fasta_file in "${INPUT_FILES[@]}"; do
    # Extract name from filename
    gene_name=$(basename "$fasta_file" .fasta)
    GENE_NAMES+=("$gene_name")
    
    # Get length
    gene_length=$(seqkit fx2tab -l "$fasta_file" 2>/dev/null | head -n 1 | awk -F'\t' '{print $4}')
    GENE_LENGTHS+=("$gene_length")
done


# Main concat logic
while IFS= read -r taxon; do
	[ -z "$taxon" ] && continue
	concat_seq=""
    
	for i in "${!INPUT_FILES[@]}"; do
        	fasta_file="${INPUT_FILES[$i]}"
        	gene_length="${GENE_LENGTHS[$i]}"
        	seq=$(seqkit grep -r -n -p "$taxon" "$fasta_file" 2>/dev/null | seqkit seq -s -w 0)
		if [ -n "$seq" ]; then
            		concat_seq="${concat_seq}${seq}"
        	else
            		missing_data=$(printf 'N%.0s' $(seq 1 $gene_length))
            		concat_seq="${concat_seq}${missing_data}"
        	fi
    	done
    echo ">${taxon}" > "${WORK_DIR}/${taxon}.fasta"
    echo "$concat_seq" >> "${WORK_DIR}/${taxon}.fasta"
    
done < "$CANONICAL_TAXA_LIST"

# print supermatrix to stdout
cat "${WORK_DIR}"/*.fasta

# print partition file to stderr
echo "#NEXUS" >&2
echo "begin sets;" >&2

current_position=1
for i in "${!GENE_NAMES[@]}"; do
    gene_name="${GENE_NAMES[$i]}"
    gene_length="${GENE_LENGTHS[$i]}"
    end_position=$((current_position + gene_length - 1))
    
    echo "  charset ${gene_name} = ${current_position}-${end_position};" >&2
    
    current_position=$((end_position + 1))
done

echo "end;" >&2
